(source gnu)
(source melpa)
(source marmalade)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "rbenv")
;;(depends-on "jekyll")
(depends-on "hyde")
(depends-on "psvn")
